services:
 rocketchat:
  image: ${IMAGE}:${RELEASE}
  restart: always
  labels:
    traefik.enable: "true"
    traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
    traefik.http.routers.rocketchat.tls: "true"
    traefik.http.routers.rocketchat.entrypoints: https
    traefik.http.routers.rocketchat.tls.certresolver: le
  volumes:
    - ./uploads:/app/uploads
  environment:
    PORT: ${PORT}
    ROOT_URL: ${ROOT_URL}
    MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
    MAIL_URL: ${MAIL_URL}
  depends_on:
    - mongodb
  ports:
    - "${BIND_IP}:${HOST_PORT}:${PORT}"


 mongodb:
  image: ${MONGODB_IMAGE}:${MONGODB_VERSION}
  restart: always
  volumes:
    - ${MONGODB_HOST_PATH}:${MONGODB_BITNAMI}
  environment:
    MONGODB_REPLICA_SET_MODE: primary
    MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME}
    MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER}
    MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST}
    MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER}
    MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME}
    MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL}
    ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}